# Generated by Django 5.0.3 on 2024-04-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0002_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cards',
        ),
        migrations.DeleteModel(
            name='session',
        ),
    ]
